[window]
dimensions = { columns = 200, lines = 100 }
decorations = "Buttonless"
blur = true
opacity = 0.8
startup_mode = "SimpleFullscreen"
decorations_theme_variant = "Dark"
dynamic_padding = true
padding = { x = 20, y = 20 }
option_as_alt = "Both"

[font]
# normal = { family = "FiraCode Nerd Font", style = "Regular" }
# bold = { family = "FiraCode Nerd Font", style = "Bold" }
# italic = { family = "FiraCode Nerd Font", style = "Italic" }
# bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }

size = 12
offset = { x = 0, y = 5 }

[cursor]
style = { shape = "Block", blinking = "On"}

[scrolling]
history = 10000

[env]
TERM = "xterm-256color"
